# 服务名称
spring:
  application:
    name: eureka-server
  security:
    user:
      name: hello
      password: world

# 服务端口
server:
  port: 9000

# Eureka配置
eureka:

  client:
    #是否将自己作为客户端注册到注册中心(缺省true), 单点设置为false
    registerWithEureka: false
    #是否从注册中心获取注册信息(缺省true), 单点设置为false
    fetchRegistry: false
    #serviceUrl:
    #  defaultZone: http://localhost:${server.port}/eureka/

    server:
      #是否开启自我保护模式(缺省true), 开发阶段建议设置为false
      enable-self-preservation: true
      #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
      eviction-interval-timer-in-ms: 10000

