config:
  # 集群地址列表
  serverA: eureka-server-9001.com #127.0.0.1
  serverB: eureka-server-9002.com #127.0.0.1
  serverC: eureka-server-9003.com #127.0.0.1

  # 集群端口列表
  portA: 9001
  portB: 9002
  portC: 9003

# 服务名称
spring:
  application:
    name: eureka-server
  security:
    user:
      name: hello
      password: world

server:
  # 服务端口
  port: ${config.portA}

# Eureka配置
eureka:

  instance:
    hostname: eureka-server-${server.port}.com
    instance-id: eureka-server-${server.port}
    #prefer-ip-address: true

  client:
    #是否将自己作为客户端注册到注册中心(缺省true), 单点设置为false
    #registerWithEureka: false
    #是否从注册中心获取注册信息(缺省true), 单点设置为false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: "http://${spring.security.user.name}:${spring.security.user.password}@${config.serverB}:${config.portB}/eureka/, \
                    http://${spring.security.user.name}:${spring.security.user.password}@${config.serverC}:${config.portC}/eureka/"

  server:
    #是否开启自我保护模式(缺省true), 开发阶段建议设置为false
    enable-self-preservation: true
    #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 10000

