#服务名称
spring:
  application:
    name: springcloud-eureka

#服务端口号
server:
  port: 9000

#Eureka配置
eureka:
  client:
    #是否把自己作为服务注册到其他服务注册中心
    registerWithEureka: false
    #是否从其他的服务中心同步服务列表
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

